### ISSUE TITLE
angular-cli version does not show scroll-bar

### ISSUE THREAD

**Issue by antrikshpatel** [creativetimofficial/material-dashboard-pro-angular#14]
Without any modifications to angular-cli, I did npm start. The scrollbar does not appear on any of the views.

**Comment by alexandru-paduraru** [comment]
@antrikshpatel thank you for using our product. Can you please let us know which OS you are using and what Browser?

Best,
Alex

**Comment by antrikshpatel** [comment]
@alexandru-paduraru 
OS: Windows 10
Browser: Chrome and Microsoft Edge

**Comment by akosbordas** [comment]
I had the same problem. I managed to make it work. (Btw. I have to tell you that it is a really ugly way how you are using angular together with jQuery.) Instead of using jQuery it's better to add `ngx-perfect-scrollbar` to package.json or simply  execute the following code `npm install ngx-perfect-scrollbar --save`. When it's done you can configure perfect scrollbar in your AppModule like this:
```
import { PerfectScrollbarModule } from 'ngx-perfect-scrollbar';
import { PerfectScrollbarConfigInterface } from 'ngx-perfect-scrollbar';

const PERFECT_SCROLLBAR_CONFIG: PerfectScrollbarConfigInterface = {
  suppressScrollX: true
};

@NgModule({
  ...
  imports: [
    ...
    PerfectScrollbarModule.forRoot(PERFECT_SCROLLBAR_CONFIG)
  ]
})
```

From here you can use scrolling anywhere in your app. If you want the main panel to be scrollable you should add the corresponding directive to the element.` <div class="main-panel" [perfect-scrollbar]>` I hope this helps. 
Ps.: After this I would get rid of all perfect-scrollbar dependencies which is jQuery related. It won't be useful anymore.

**Comment by alexandru-paduraru** [comment]
@akosbordas thank you for the information and for giving us a solution. We will test it today and see if it is working fine. We used the perfect-scrollbar in v1.0.1 via package.json and we've got a lot of feedback from the users that it is giving an "infinite scroll" in different cases. We used the 0.7.0 version. Then we moved to the old 0.6.13 importing it as a separate library. This is the npm version that we used: https://www.npmjs.com/package/perfect-scrollbar

I agree 100% with your way of integrating it, but we need to make some tests to see if it is giving that "infinite scroll".

Can you please let us know if you've seen any weird behaviour after you add like that?

**Comment by alexandru-paduraru** [comment]
@akosbordas just wanted to update the version with your suggestion but it seems I'm doing something wrong:

<img width="1440" alt="screen shot 2017-05-25 at 08 06 35" src="https://cloud.githubusercontent.com/assets/2517758/26436722/288664d8-4121-11e7-924f-1ea531bd0256.png">

Any ideas?

**Comment by akosbordas** [comment]
@alexandru-paduraru No I haven't seen that "infinite scrolling" behavior before. The error says that angular does not recognize the directive. That's because you probably haven't added `PerfectScrollbarModule.forRoot(PERFECT_SCROLLBAR_CONFIG)` to your sidebar module. I wrote above that you have to add it to your AppModule but it's not the case of course if you want to use it in other modues as well.

**Comment by alexandru-paduraru** [comment]
@akosbordas got it, we will check with your suggestion again. BTW, do you know how we should add the conditions with the [perfect-scrollbar] to be active only when we are on Windows platform? The issue is present only in Windows because we want to replace the regular ugly scrollbar. On MacOS, Ubuntu, iOS, Android the scrollbars are looking fine. 

Best,
Alex

**Comment by akosbordas** [comment]
I work on Windows as well. I have no issues with the scroll bar.  What is your exact Problem?

**Comment by alexandru-paduraru** [comment]
@akosbordas we want to activate the Perfect scrollbar only when we are on Windows, not on Mac. Mac, Ubuntu, iOS and Android have their own scrollbars which are looking good. Windows has an ugly bar which is replaced by Perfectscrollbar. So we want to activate the library only on windows, not on the other platform. Got it? :D

**Comment by akosbordas** [comment]
Yes I got it for the first time too. But this is not changing the fact what you are doing in your components is a really ugly hack, got it? :D And I'm saying this as your customer....who has to work with your code.
That's why I suggested to use everywhere the perfect scrollbar, so you don't need these and the website will look the same on every platform. What if I come up with an issue tomorrow that the scrollbar does not look like the same as on Android or Mac? (It can happen any time that the scrollbar changes on android with an update) Will you start hack the scrollbar look again on windows (inceasing the unnecessary code)? :D

This is not the angular way how you deal with things:

```
        let body = document.getElementsByTagName('body')[0];
        var isWindows = navigator.platform.indexOf('Win') > -1 ? true : false;
        if (isWindows){
           // if we are on windows OS we activate the perfectScrollbar function
            body.classList.add("perfect-scrollbar-on");
        } else {
            body.classList.add("perfect-scrollbar-off");
        }
```

**Comment by alexandru-paduraru** [comment]
@akosbordas yes, you're right, actually don't remember now what was the reason for adding the PerfectScrollbar just for windows and not on all the platforms. I think 2 years ago when we created our first Dashboard there were some compatibility issues with Ubuntu. We will check if that is the case these days, if it is working fine then we will not add that hack, we will have it activated on all the platforms.

Best,
Alex

**Comment by MohsinShaikh89** [comment]
Can anyone share cli version of code?

**Comment by alexandru-paduraru** [comment]
@MohsinShaikh89 the CLI version is in the same archive with the plain ng2 from our website if you have purchased a license. Please check it there and let us know if everything is fine.

Best,
Alex
