### ISSUE TITLE
Datatables.net style issue on 2.0.1 BS4

### ISSUE THREAD

**Issue by n1lptr** [creativetimofficial/material-dashboard-pro-angular#240]
I have issue with datatables.net paging bar style

[](url)
![capture](https://user-images.githubusercontent.com/34329392/39399064-757c74e6-4b41-11e8-92c7-aa965d35b1c3.PNG)

**Comment by chelaruc** [comment]
Hi, @n1lptr ! Thank you for using our product. All you have to do is to replace the file from this archive with your current file:
[_pagination.scss.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1967569/_pagination.scss.zip)

This will be fixed in next version.

All the best,
Ciprian
