### ISSUE TITLE
routerLink on initMenu.js cloned elements refreshes the page when clicked

### ISSUE THREAD

**Issue by prodia4** [creativetimofficial/material-dashboard-pro-angular#3]
I have a main page that has a navbar whose '.navbar-collapse' elements get cloned and put to '.nav-mobile-menu' by 'initMenu.js'.

But the problem is that the routerLinks attached to those elements don't act as expected when they're cloned and moved to '.nav-mobile-menu'. When they are not collapsed they route to the expected pages like a single page app, but when they are moved to the side and clicked they cause the whole page to refresh.

I'm guessing this has to do with jquery not being able to clone Angular's routerLink binding but I'm not sure.. 

Would appreciate it if you could give an answer to this problem.

**Comment by alexandru-paduraru** [comment]
@prodia4 thank you for using our product and for showing the issue. As we said in the email, we will try to replicate the issue using the routerLink and then find a solution for you. We will come with something on Monday when we will be in the office and have all the necessary tools to test this.

Best,
Alex

**Comment by dragosct10** [comment]
Hi @prodia4! I finished to fix your issue and I will attach the file `initMenu.js` which is modified and what you have to do is to go in `assets/js/init/initMenu.js` and replace the old file with the new one that I gave it to you. Hope that will help you! 

Regards,
Dragos

[initMenu.js.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/910155/initMenu.js.zip)

**Comment by prodia4** [comment]
Hello,
I'm sorry but it didn't solve the problem. Also, there's the same problem
in initBootstrapNavbarMenu but nothing was changed there.
Could you explain to me what you thought was the cause of the problem?

2017-04-10 22:25 GMT+09:00 dragosct <notifications@github.com>:

**Comment by dragosct10** [comment]
Hi @prodia4! Thank you for the information, it seems we updated just the version for the dashboard, not the one from the login/register pages (initBootstrapNavbarMenu). 

Now I updated the file `initMenu.js` with changes of the code inside of function `initBootstrapNavbarMenu` too. Now the elements from the menu are not cloned anymore and if you add a function like `onclick="alert('something')"` it is working fine in the regular navbar and also in the mobile menu sidebar. 

Please check the file and let us know if that is solving the issue. Otherwise please tell us exactly what you want to achieve and what is not working as you expected so we can identify better your issue.

[initMenu.js.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/913304/initMenu.js.zip)

Best,
Dragos

**Comment by prodia4** [comment]
Hi again, sorry but the problem i mentioned is different from the one
you've addressed.

As you said, onclick="alert('something')" now works, but Angular 2's
(click) does not.

for example, I have a

<li class="pointer" *ngIf="auth.isLoggedIn()" routerLinkActive="active">
    <a (click)="auth.logout()">
        <i class="material-icons">settings_power</i> Logout
    </a>
</li>

which won't work when it's collapsed.

I think a better solution is to just change the css, not the html and I've
been trying that but it's not easy.

2017-04-11 22:26 GMT+09:00 dragosct <notifications@github.com>:

**Comment by alexandru-paduraru** [comment]
@prodia4 is is something that (click) is doing and it is depending on the DOM? I mean, it has to be in the same position where it was initially added? I've found also this answer for the case of (click) not working, it seems Angular is not reading from an element that is added and removed from the DOMhttp://stackoverflow.com/questions/42779573/click-event-is-not-working-in-angular-2

1. Let's try something: go to Desktop mode, then go to mobile, then again to desktop and click on it and let us know if it is working or not.

Can you please share with us a link to your project? Maybe we can figure out this error.

Best,
Alex

**Comment by prodia4** [comment]
Yep that still works because it hides the element based on CSS, not removing it from the DOM.

I think the solution is to either 

1. Change the CSS based on window size to make it behave as it does now. 
or
2. Make a separate Angular component for the sidebar and make it show up needed.

I think option number 1 would be a simpler approach for now. 

How about not utilizing initMenu.js at all and achieving the same effect with CSS?

(I'm sorry for not being able to share the link to the project. It's in a private repo. But I'll write down the relevant parts here.)

```html
home.component.html

<home-navbar-cmp [title]="title"></home-navbar-cmp>
<div class="wrapper wrapper-full-page">
    <router-outlet></router-outlet>
</div>
```

```typescript
home.component.ts

@Component({
  moduleId: module.id,
  templateUrl: 'home.component.html',
  styleUrls: ['home.component.css']
})
export class HomeComponent implements OnInit {
  constructor() {
  }

  ngOnInit() {
    $.getScript('assets/js/init/initMenu.js');
  }
}
```

```html
navbar.component.html

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li *ngIf="auth.isLoggedIn()" routerLinkActive="active">
                    <a routerLink="/dashboard">
                        <i class="material-icons">dashboard</i> Dashboard
                    </a>
                </li>
                <li class="pointer" *ngIf="auth.isLoggedIn()" routerLinkActive="active">
                    <a (click)="auth.logout()">
                        <i class="material-icons">settings_power</i> Logout
                    </a>
                </li>
                <li *ngIf="!auth.isLoggedIn()" routerLinkActive="active">
                    <a routerLink="/register">
                        <i class="material-icons">person_add</i> Register
                    </a>
                </li>
                <li *ngIf="!auth.isLoggedIn()" routerLinkActive="active">
                    <a routerLink="/login">
                        <i class="material-icons">fingerprint</i> Login
                    </a>
                </li>
            </ul>
        </div>
```

**Comment by alexandru-paduraru** [comment]
@prodia4 the option 1 with only the CSS changes doesn't work with the current implementation because the navbar and the sidebar are placed in different divs:

<img width="1440" alt="screen shot 2017-04-19 at 19 46 49" src="https://cloud.githubusercontent.com/assets/2517758/25191652/f5cbd590-2538-11e7-9e2e-53ae4608065f.png">

So we cannot move that inside the sidebar to be visible on mobile without altering the DOM.

Another option would be to create a second navbar for mobile which will act as the default navbar from the desktop.

Will come back later tomorrow with this option. Hope that will work fine :D

Keep in touch,
Alex
