### ISSUE TITLE
The DatePicker "Day" view is not styled.

### ISSUE THREAD

**Issue by kujtimiihoxha** [creativetimofficial/material-dashboard-pro-angular#37]
I am having issues with the datepicker day style, I can see that in the demo http://md-pro-angular2.creative-tim.com/#/forms/extended the picker is working just fine but in my local version it does not work.

I have not modified the source files in any way.

<img width="828" alt="screen shot 2017-07-19 at 3 37 54 pm" src="https://user-images.githubusercontent.com/14311743/28369558-4595faaa-6c98-11e7-9840-b10348daeb4f.png">

**Comment by chelaruc** [comment]
Hi @kujtimiihoxha, 

Thank you for using our product. We know about this bug and will be fixed in the next update. To resolve it, you'll need to replace the following scss file: 'src/assets/sass/material-dashboard/plugins/_plugin-datetime-picker.scss' and compile the scss file. I will attach the file which you will replace the current one. Tell me if this worked for you!
[_plugin-datetime-picker.scss.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1159368/_plugin-datetime-picker.scss.zip)

Keep in touch,

Ciprian

**Comment by kujtimiihoxha** [comment]
@chelaruc thank you very much, it works perfectly 😄
