### ISSUE TITLE
moving tab issue with sidebar

### ISSUE THREAD

**Issue by bikramchoudhury** [creativetimofficial/material-dashboard-pro-angular#90]
Hi, Team
on click of sidebar navigation, moving tab is working properly. But if you will try to navigate from one component to another component with code, then moving tab is not working. And if you 'll reload the browser, then moving tab appearing at its appropriate position.

if you are at custom.component.ts
```
edit(rowId:string){
	if(!this.utils.isEmpty(rowId)){
		let transient:any = _.findWhere(this.rowData.dataRows,{_id:rowId});
		if (transient) {
			if(typeof(Storage) != 'undefined'){
				localStorage.setItem('dataHash',JSON.stringify(transient));
			}
			this.routes.navigate(['components/buttons']);
		}
		
	}
}
``` 
can you please help me to find out the issue?

**Comment by alexandru-paduraru** [comment]
@bikramchoudhury thank you for using our product. Can you please let us know which version you have? We removed the Moving Tab in the v1.4.x because it was causing a lot of issues with jQuery. We are looking to migrate it to Native Angular code.

Best,
Alex

**Comment by bikramchoudhury** [comment]
@alexandru-paduraru  Actually I am not aware of the version, but I am sure the version will be less than 1.4. So can you please tell me how I could fix it.

Thanks
Bikram

**Comment by alexandru-paduraru** [comment]
@bikramchoudhury since each version is different and have structure changes, we need to know exactly the version so we know what to check in order to identify the bug. You can find the version in scss/material-dashboard.scss or you can send us a link to your webapp and we will find it. 

In the meantime, if you have the file `assets/js/sidebar-moving-tab.js` you will see 2 functions:

```js
    setMovingTabPosition();
    animateMovingTab();
```

Those need to be called after you change the route, so the Moving Tab will calculate it's new position and then will be animated from the initial to the latest position.

Please let us know your status.

Best,
Alex
